name: Build & Release Aseprite

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: aseprite/build
          key: build-${{ matrix.os }}-${{ github.ref_name }}

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            libpixman-1-dev libfreetype6-dev libharfbuzz-dev zlib1g-dev \
            libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev

      - name: Install Dependencies (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: brew install cmake ninja ccache pkg-config

      - name: Install OpenSSL (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: choco install -y openssl --version=1.1.1.2000

      - name: Install Ninja
        uses: aseprite/get-ninja@main

      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'

      - name: Configure CMake
        shell: bash
        working-directory: aseprite
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DLAF_BACKEND=skia \
            -DENABLE_SCRIPTING=on \
            -DENABLE_TESTS=OFF

      - name: Build
        shell: bash
        working-directory: aseprite
        run: cmake --build build --config RelWithDebInfo --parallel

      - name: Copy OpenSSL DLLs (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        continue-on-error: true
        run: |
          $opensslBin = "C:\Program Files\OpenSSL\bin"
          try {
            Copy-Item "$opensslBin\libcrypto-1_1-x64.dll" -Destination aseprite/build/bin/ -ErrorAction Stop
            Copy-Item "$opensslBin\libssl-1_1-x64.dll" -Destination aseprite/build/bin/ -ErrorAction Stop
            Write-Host "✅ Copied OpenSSL DLLs"
          } catch {
            Write-Warning "⚠️ OpenSSL DLLs not found — continuing anyway. Download and install OpenSSL 1.1.1.2000 from https://community.chocolatey.org/packages/openssl/1.1.1.2000"
          }

      - name: Package Build
        shell: bash
        run: |
          cd aseprite/build
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            7z a ../aseprite-${{ github.ref_name }}-windows-full.zip .
            7z a ../aseprite-${{ github.ref_name }}-windows-bin.zip ./bin
          elif [[ "${{ runner.os }}" == "Linux" ]]; then
            tar -czf ../aseprite-${{ github.ref_name }}-linux.tar.gz .
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            tar -czf ../aseprite-${{ github.ref_name }}-macos.tar.gz .
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            aseprite/*.zip
            aseprite/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
